-- Create a custom type for match status
CREATE TYPE public.match_status AS ENUM ('live', 'upcoming', 'finished');

-- Create the moviesandseries table
CREATE TABLE public.moviesandseries (
  id TEXT NOT NULL,
  slug TEXT NOT NULL,
  title TEXT NULL,
  year INTEGER NULL,
  category TEXT NULL,
  type TEXT NULL,
  rating TEXT NULL,
  genre TEXT[] NULL,
  description TEXT NULL,
  "posterUrl" TEXT NULL,
  "backdropUrl" TEXT NULL,
  "videoSources" JSONB NULL,
  "downloadLinks" JSONB NULL,
  featured BOOLEAN NULL DEFAULT false,
  "dateAdded" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  CONSTRAINT moviesandseries_pkey PRIMARY KEY (id),
  CONSTRAINT moviesandseries_slug_key UNIQUE (slug)
);

-- Enable Row Level Security
ALTER TABLE public.moviesandseries ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access
CREATE POLICY "Allow public read access" ON public.moviesandseries
FOR SELECT USING (true);

-- Policy: Allow full access for authenticated users (for admin operations)
CREATE POLICY "Allow all for authenticated" ON public.moviesandseries
FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Create the live_matches table
CREATE TABLE public.live_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    team1_name TEXT NOT NULL,
    team1_logo TEXT NULL,
    team2_name TEXT NOT NULL,
    team2_logo TEXT NULL,
    tournament TEXT NULL,
    start_time TIMESTAMP WITH TIME ZONE NULL,
    status public.match_status NULL,
    stream_links JSONB NULL,
    CONSTRAINT live_matches_pkey PRIMARY KEY (id)
);

-- Enable Row Level Security
ALTER TABLE public.live_matches ENABLE ROW LEVEL SECURITY;

-- Policy: Allow public read access
CREATE POLICY "Allow public read access" ON public.live_matches
FOR SELECT USING (true);

-- Policy: Allow full access for authenticated users (for admin operations)
CREATE POLICY "Allow all for authenticated" ON public.live_matches
FOR ALL TO authenticated USING (true) WITH CHECK (true);